# -*- coding: utf-8 -*-
"""project_probability.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-CsLRJWEdYPcmWda2eiLzs9MFXlbFxXF

# **ANALISIS KORELASI ANTARA RATA-RATA LAMA TAMU MENGINAP, JUMLAH PENGUNJUNG OBYEK WISATA DAN PENDAPATAN DOMESTIK REGIONAL BRUTO KABUPATEN SEMARANG**


---
"""

import pandas as pd
import numpy as np
from numpy import cov
import matplotlib.pyplot as plt
import seaborn as sns
from matplotlib.patches import Ellipse
import matplotlib.transforms as transforms
import scipy.stats as stats

import ipywidgets as widgets
from ipywidgets import interact

# Data set dari BPS
# https://semarangkab.bps.go.id/subject/16/pariwisata.html#subjekViewTab3
data = pd.DataFrame({
    'Tahun':[2016, 2017, 2018, 2019, 2020],
    'RLM':[1.09, 1.1, 1.13, 1.63, 1.03],
    'Banyak Pengunjung':[1.18, 2.86, 3.38, 2.82, 2.0],
    'PDRB Sek. Akomodasi Makan Minum':[5.59, 6.83, 7.98, 8.23, -6.6]
})

data

data.info()

data_indexed = data.set_index('Tahun')

data_indexed

data_indexed.describe().T

"""ANALISIS PELUANG PADA VARIABEL DISKRIT:
peluang terjadinya lebih dari 2 juta pengunjung pada suatu tahun

"""

total_years = len(data)
years_more_than_2m = len(data[data['Banyak Pengunjung'] > 2])
peluang = years_more_than_2m / total_years

print('Peluang terjadinya lebih dari 2 juta pengunjung adalah:', peluang)

"""ANALISIS PELUANG PADA VARIABEL CONTINUES: Peluang terjadinya pertumbuhan PDRB restoran dan akomodasi lebih dari 1,5% pada variabel "RLM"
"""

#Membuat Density Plot
sns.kdeplot(data['RLM'], shade=True)

"""Setelah memplotkan density plot, kita dapat melihat area di bawah kurva di atas nilai 1,5% untuk menghitung peluangnya.

Untuk variabel "PDRB Sek. Akomodasi Makan Minum", kita juga dapat menggunakan visualisasi seperti histogram atau density plot, namun kita harus memperhatikan nilai negatif pada variabel ini. Kita dapat memisahkan nilai negatif dan positif, dan melakukan analisis peluang terpisah untuk kedua kategori nilai tersebut. Misalnya, jika kita ingin menghitung peluang terjadinya penurunan PDRB lebih dari 5%, kita dapat menghitung berapa persentase data dengan nilai negatif yang memenuhi kriteria tersebut.

Perlu diperhatikan bahwa analisis peluang pada variabel continues biasanya melibatkan konsep probabilitas kontinu, dan dapat melibatkan penggunaan distribusi probabilitas seperti distribusi normal atau distribusi t-student. Namun, pemilihan distribusi probabilitas harus dilakukan dengan hati-hati dan didasarkan pada asumsi yang tepat untuk data yang ada.
"""

# Hitung nilai z-score untuk persentil atas 1,5%
z_score = stats.norm.ppf(0.985)

# Hitung mean dan standard deviation dari data
mean = data['RLM'].mean()
std = data['RLM'].std()

# Hitung batas atas untuk pertumbuhan PDRB restoran dan akomodasi yang lebih dari 1,5%
upper_limit = mean + z_score * std * (1 + 1/len(data))**0.5

# Hitung peluang terjadinya pertumbuhan PDRB restoran dan akomodasi lebih dari 1,5%
peluang = 1 - stats.norm.cdf(upper_limit, loc=mean, scale=std)

print('Peluang terjadinya pertumbuhan PDRB restoran dan akomodasi lebih dari 1,5% adalah:', peluang)

"""#UJI KORELASI ANTARA VARABEL RLM, BANYAK PENGUNGJUNG DAN PDRB"""

import pandas as pd
from scipy.stats import pearsonr

corr_RLM_PDRB, _ = pearsonr(data['RLM'], data['PDRB Sek. Akomodasi Makan Minum'])
corr_BP_PDRB, _ = pearsonr(data['Banyak Pengunjung'], data['PDRB Sek. Akomodasi Makan Minum'])

print('Korelasi antara RLM dan PDRB: %.3f' % corr_RLM_PDRB)
print('Korelasi antara Banyak Pengunjung dan PDRB: %.3f' % corr_BP_PDRB)

"""*) Korelasi antara RLM dan PDRB sebesar 0.472 menunjukkan adanya hubungan yang positif dan cukup kuat antara RLM dan PDRB. Artinya, semakin besar nilai RLM, maka kemungkinan besar PDRB juga akan semakin besar.

*) Korelasi antara Banyak Pengunjung dan PDRB sebesar 0.426 menunjukkan adanya hubungan yang positif dan sedang antara Banyak Pengunjung dan PDRB. Artinya, semakin banyak pengunjung yang datang, maka kemungkinan besar PDRB juga akan semakin besar.
"""



"""# UJI HIPOTESIS
Hipotesis :
H0 = ada korelasi antara variabel Rata-rata
Lama Tamu Menginap dan PDRB sektor
Akomodasi, makan dan minum
Ha = tidak ada korelasi antara variabel Ratarata Lama Tamu Menginap dan PDRB
sektor Akomodasi, makan dan minum.


•Dengan n=5 dan α=0,01.


"""

x = data['RLM']
y = data['PDRB Sek. Akomodasi Makan Minum']

# Menghitung korelasi Pearson dan p-value
corr, p_value = pearsonr(x, y)

# Menampilkan hasil uji hipotesis
alpha = 0.01
if p_value < alpha:
    print("Dapat menolak H0, artinya tidak ada korelasi antara variabel Rata-rata Lama Tamu Menginap dan PDRB sektor Akomodasi, makan dan minum")
else:
    print("Tidak dapat menolak H0, artinya ada korelasi antara variabel Rata-rata Lama Tamu Menginap dan PDRB sektor Akomodasi, makan dan minum")